apiVersion: v1
kind: Service
metadata:
  name: counter
  labels:
    app: counter
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: counter
    tier: frontend
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: counter
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: counter
  minReplicas: 2
  maxReplicas: 20
  targetCPUUtilizationPercentage: 50
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter
  labels:
    app: counter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: counter
      tier: frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: counter
        tier: frontend
    spec:
      containers:
        - image: wiardvanrij/huiswerk:1
          name: counter
          resources:
            limits:
              memory: "150Mi"
              cpu: "100m"
            requests:
              cpu: "10m"
              memory: "100Mi"                            
          env:
            - name: COUNTER_RECHECKAMOUNT
              value: "20"
            - name: COUNTER_HEALTHCHECKTIME
              value: "500"
            - name: COUNTER_REDISHOST
              value: "redis.redis:6379"